In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])

In [3]:
print(x)

[1 2 3 4 5]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [38]:
y=np.array([[1,2,3],[4,5,6]])

In [39]:
print(y)

[[1 2 3]
 [4 5 6]]


In [40]:
y=np.matrix(y)

In [42]:
#print(np.dot(x,y))

In [43]:
z=np.array([[7,8],[9,10],[11,12]])

In [44]:
z=np.matrix(z)

In [47]:
import time


In [52]:

print(y*z)


[[ 58  64]
 [139 154]]
--- 0.0 seconds ---


In [51]:

print(np.dot(y,z))

--- 0.0 seconds ---
[[ 58  64]
 [139 154]]


In [55]:
a=np.array([5,4,3,2,1])

In [56]:
a*x

array([5, 8, 9, 8, 5])

In [58]:
np.dot(a,x)

35

In [73]:
ss=np.concatenate((x.reshape(len(x),1),a.reshape(len(a),1)),1)

In [65]:
print(type(x))

<class 'numpy.ndarray'>


In [75]:
print(ss.shape)

(5, 2)


In [76]:
print(ss)

[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]]


In [77]:
np.diagonal(z)

array([ 7, 10])

In [78]:
print(z)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [90]:
z.diagonal(0,0,1)

matrix([[ 7, 10]])

In [94]:
a.sort()

In [92]:
print(a)

[1 2 3 4 5]


In [103]:
lst2=[34,17,51]


In [97]:
print(sorted(lst2))

[17, 34, 51]


In [98]:
print(lst2)

[34, 17, 51]


In [104]:
lst2=np.array(lst2)

In [108]:
np.searchsorted(lst2,300)

3